// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: samba_admin.proto

package proto_samba_management

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SambaAllocationClient is the client API for SambaAllocation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SambaAllocationClient interface {
	AllocateSambaShare(ctx context.Context, in *RequestShambaShare, opts ...grpc.CallOption) (*SambaResponse, error)
}

type sambaAllocationClient struct {
	cc grpc.ClientConnInterface
}

func NewSambaAllocationClient(cc grpc.ClientConnInterface) SambaAllocationClient {
	return &sambaAllocationClient{cc}
}

func (c *sambaAllocationClient) AllocateSambaShare(ctx context.Context, in *RequestShambaShare, opts ...grpc.CallOption) (*SambaResponse, error) {
	out := new(SambaResponse)
	err := c.cc.Invoke(ctx, "/SambaAllocation/AllocateSambaShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SambaAllocationServer is the server API for SambaAllocation service.
// All implementations must embed UnimplementedSambaAllocationServer
// for forward compatibility
type SambaAllocationServer interface {
	AllocateSambaShare(context.Context, *RequestShambaShare) (*SambaResponse, error)
	mustEmbedUnimplementedSambaAllocationServer()
}

// UnimplementedSambaAllocationServer must be embedded to have forward compatible implementations.
type UnimplementedSambaAllocationServer struct {
}

func (UnimplementedSambaAllocationServer) AllocateSambaShare(context.Context, *RequestShambaShare) (*SambaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocateSambaShare not implemented")
}
func (UnimplementedSambaAllocationServer) mustEmbedUnimplementedSambaAllocationServer() {}

// UnsafeSambaAllocationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SambaAllocationServer will
// result in compilation errors.
type UnsafeSambaAllocationServer interface {
	mustEmbedUnimplementedSambaAllocationServer()
}

func RegisterSambaAllocationServer(s grpc.ServiceRegistrar, srv SambaAllocationServer) {
	s.RegisterService(&SambaAllocation_ServiceDesc, srv)
}

func _SambaAllocation_AllocateSambaShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestShambaShare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SambaAllocationServer).AllocateSambaShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SambaAllocation/AllocateSambaShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SambaAllocationServer).AllocateSambaShare(ctx, req.(*RequestShambaShare))
	}
	return interceptor(ctx, in, info, handler)
}

// SambaAllocation_ServiceDesc is the grpc.ServiceDesc for SambaAllocation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SambaAllocation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SambaAllocation",
	HandlerType: (*SambaAllocationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllocateSambaShare",
			Handler:    _SambaAllocation_AllocateSambaShare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "samba_admin.proto",
}
